// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4L7f_jzz7yW0QtB1CdyhAZEuqXmA9IGQ',
    appId: '1:11961631583:web:427c570c2eace4eda2acea',
    messagingSenderId: '11961631583',
    projectId: 'tastybite-1bd69',
    authDomain: 'tastybite-1bd69.firebaseapp.com',
    storageBucket: 'tastybite-1bd69.appspot.com',
    measurementId: 'G-Y0DJ2PBLNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_i1P30OsFc-LUN6i_k5Ma6QF2vD9waQg',
    appId: '1:11961631583:android:281e609b4693631aa2acea',
    messagingSenderId: '11961631583',
    projectId: 'tastybite-1bd69',
    storageBucket: 'tastybite-1bd69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS2Vva3AX0PHmeiNQqsGZI-SwbtgeLhiw',
    appId: '1:11961631583:ios:8a7b3aa3d1e7a2cea2acea',
    messagingSenderId: '11961631583',
    projectId: 'tastybite-1bd69',
    storageBucket: 'tastybite-1bd69.appspot.com',
    iosBundleId: 'com.example.tastybite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS2Vva3AX0PHmeiNQqsGZI-SwbtgeLhiw',
    appId: '1:11961631583:ios:34f317cadfc83ca5a2acea',
    messagingSenderId: '11961631583',
    projectId: 'tastybite-1bd69',
    storageBucket: 'tastybite-1bd69.appspot.com',
    iosBundleId: 'com.example.tastybite.RunnerTests',
  );
}
